version: '3'
services:
  app:
    container_name: app-node
    image: node:lts-alpine
    working_dir: /app
    environment:
      APP_MODE: ${APP_MODE:-dev}
      APP_PATH: ${APP_PATH:-.}
    volumes:
      - ${APP_PATH:-.}:/app
    # entrypoint: "npm install"
    command: "npm install"
    # command: "npm run serve"
    # depends_on:
    #   - api
